# Generated by Django 5.0.7 on 2024-07-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authors',
            table='authors',
        ),
        migrations.AlterModelTable(
            name='books',
            table='books',
        ),
    ]
